### ISSUE TITLE
small typo in explaining exponential of  a log

### ISSUE THREAD

**Issue by pvesk** [mbjoseph/mbjoseph.github.io#4]
In section the log of the joint distribution, this doesn't render correctly:

> `This is true because e^log(x)=x
the '=x' is incorrectly in the exponent

**Comment by mbjoseph** [comment]
Ah nice! Thank you @pvesk! Should be fixed with https://github.com/mbjoseph/mbjoseph.github.io/commit/91f6fbd7181333d965edc26f7bc0404752a447e3
