### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by joshua-goldberg** [mbjoseph/mbjoseph.github.io#5]
Very nice explanation. I noticed a small typo where you give the exp(log(x)) = x rule. The '= x' appears in the superscript, but should probably have the usual baseline.

**Comment by mbjoseph** [comment]
Thanks @joshua-goldberg! Fixed with https://github.com/mbjoseph/mbjoseph.github.io/commit/91f6fbd7181333d965edc26f7bc0404752a447e3
