### ISSUE TITLE
Adapting your comm_occ.txt model for dynamic multispecies occupancy

### ISSUE THREAD

**Issue by ajdennhardt** [mbjoseph/mbjoseph.github.io#6]
Hi Maxwell,

The following queries are in reference to the dynamic multispecies occupancy model you previously described [here](https://mbjoseph.github.io/posts/2018-12-22-dynamic-community-occupancy-model-jags/) and [here](https://github.com/mbjoseph/mbjoseph.github.io/blob/master/_posts/2018-12-22-dynamic-community-occupancy-model-jags/com_occ.txt). I have attempted to incorporate many of your ideas in candidate models of my own toward describing multispecies bird dynamics in a temperate agroforested system.

Regarding your example, if you have the time and interest available, then I hoped you might be willing to answer some questions:
- Is beta[i] acting similar to how an intercept would in a conventional regression model?
- Is rho[i] analogous to a correlation coefficient between co-occurring species in the community?
- Is it possible/advisable to add linear effects of covariates in an occupancy submodel that contains both beta[i] and rho[i]? If so, then do you have recommendations about what that might look like?
- Is it possible/advisable to add interaction effects between two or more co-occurring species in an occupancy submodel that contains both beta[i] and rho[i]? If so, then do you have recommendations about what that might look like?
- Finally, if my own model's intercept was split into two parts, noting species-specific occupancy differences between treatments (e.g., beta0.trt1[i] * Indicator[j] + beta0.trt2[i] * Indicator[j] for the i-th species and j-th site, where Indicator is 0/1 coded), then how would beta[i] and rho[i] need to be adjusted, if at all?

Please let me know if I can clarify anything above, and I sincerely thank you for your time. I was unsure of where to contact you about the aforementioned ideas, and so I started here. I hope that's okay, and I look forward to hearing back from you soon.

Sincerely,
Andrew

P.S. Do you also have a preferred citation for your example(s)?

**Comment by ajdennhardt** [comment]
I recently found some guidance in Kery and Royle (2020). Perhaps it's unnecessary to address my previous questions.

**Comment by mbjoseph** [comment]
Hey @ajdennhardt - glad you are finding this useful. 

- *Is beta[i] acting similar to how an intercept would in a conventional regression model?* 

Yes - you could think of that as an "intercept" parameter for occupancy probabilities. It's also the logit probability of colonization (think about what psi is when the previous timestep's z value is 0 for [this line](https://github.com/mbjoseph/mbjoseph.github.io/blob/master/_posts/2018-12-22-dynamic-community-occupancy-model-jags/com_occ.txt#L37)). 

- *Is rho[i] analogous to a correlation coefficient between co-occurring species in the community?* 

No - this model doesn't include explicit correlation parameters to represent associations among species. Here, `rho` is a parameter that represents the effect of the previous time step's occupancy probability: https://github.com/mbjoseph/mbjoseph.github.io/blob/master/_posts/2018-12-22-dynamic-community-occupancy-model-jags/com_occ.txt#L27

- *Is it possible/advisable to add linear effects of covariates in an occupancy submodel that contains both beta[i] and rho[i]? If so, then do you have recommendations about what that might look like?* 

Yes you can definitely add covariates to the occupancy model, even with those parameters. IIRC there might be some dynamic occupancy examples in the Royle/Dorazio book (ch 9) that do this: https://www.mbr-pwrc.usgs.gov/pubanalysis/roylebook/chapters.htm 

- *Is it possible/advisable to add interaction effects between two or more co-occurring species in an occupancy submodel that contains both beta[i] and rho[i]? If so, then do you have recommendations about what that might look like?* 

I'm not sure I know what you mean by interaction effects between species. If you wanted to model correlations among species, you could do it, but it might get complicated. You might find some useful tidbits in this paper: https://doi.org/10.1002/ecy.2754

- *Finally, if my own model's intercept was split into two parts, noting species-specific occupancy differences between treatments (e.g., beta0.trt1[i] * Indicator[j] + beta0.trt2[i] * Indicator[j] for the i-th species and j-th site, where Indicator is 0/1 coded), then how would beta[i] and rho[i] need to be adjusted, if at all?* 

Are `beta0.trt1` and `beta0.trt2` redundant? If the treatment indicator is 0 you'd get `beta[i]`, and if it's one you'd get `beta[i] + beta0.trt1[i] + beta0.trt2[i]`, in which case I would guess only the sum `beta0.trt1[i] + beta0.trt2[i]` is identified. Could you get an equivalent parameterization if you do `beta[i] + beta.trt[i] * indicator[j]`?

**Comment by ajdennhardt** [comment]
Thank you for your helpful responses, @mbjoseph . The answers and resources you've provided are very straightforward and useful. 

On the last question, you're right; there was a typo. That treatment difference should read: beta0.trt1[i] * (1 - Indicator[j]) + beta0.trt2[i] * Indicator[j] , where treatment 1 sites are coded as "1" and treatment 2 sites are coded as "0." You're also correct about the correlation between species part, which I also misrepresented. I will continue to chip away at the challenges of these dynamical models. Thanks again!
