### ISSUE TITLE
Problem visualizing blog post

### ISSUE THREAD

**Issue by AurMad** [mbjoseph/mbjoseph.github.io#7]
Dear Max, 
I would be very interested to read one of your blog posts on marginalizing over discrete parameters. I have tried to read it from several browsers, but I always get a blank page.
Would you have a solution to this problem?
Kind regards,
Aurélien

**Comment by mbjoseph** [comment]
thanks @AurMad - I have no idea why this stopped rendering, but I rebuilt the site and this post seems to be back up https://mbjoseph.github.io/posts/2020-04-28-a-step-by-step-guide-to-marginalizing-over-discrete-parameters-for-ecologists-using-stan/

**Comment by AurMad** [comment]
It works. Thanks!
